name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1     
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build
        run: |
          npm install
      - name: Build
        run: |
          npm i cordova
      - name: Add cordova-android
        run: |
         npm i cordova-android
      - name: Add Platform
        run: |
         ionic cordova build android --nofetch
