name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Install Cordova
        run: |
          npm i cordova
      - name: Remove cordova res
        run: |
          npm uninstall cordova-res
      - name: Install cordova res
        run: |
          npm install -g cordova-res
      - name: Add cordova-android
        run: |
         npm i cordova-android
      
      - name: Add Platform
        run: |
         ionic cordova platform add android@10.0.0 --nofetch
